import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {prepare,hash,synchronize} from './sync-content.mjs'
function fixture(t){const root=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'blog-allowlist-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const n of ['10_Published','90_Index','00_Drafts','assets/public'])fs.mkdirSync(path.join(root,n),{recursive:true});const f={files:{},assets:{}};const write=(n,text,approved=true)=>{fs.mkdirSync(path.dirname(path.join(root,n)),{recursive:true});fs.writeFileSync(path.join(root,n),text);if(approved){const type=n.startsWith('10_Published/')?'files':'assets';const name=n.replace(/^(10_Published|assets\/public)\//,'');f[type][name]=hash(text)}fs.writeFileSync(path.join(root,'90_Index/공개승인.json'),JSON.stringify(f))};write('10_Published/index.md','---\ntitle: Home\ndate: 2026-09-12\ntags: []\ndraft: false\n---\nHome');return {root,write,f}}
test('only approved Markdown is read, never all journal files',t=>{const {root,write}=fixture(t);write('00_Drafts/private.md','PRIVATE-CANARY',false);write('10_Published/not-approved.md','PRIVATE-CANARY',false);const out=prepare(root);assert.equal(out.size,1);assert.ok(![...out.values()].join('').includes('PRIVATE-CANARY'))})
test('modified approval fails before replacing old content',t=>{const {root,write}=fixture(t);write('10_Published/index.md','changed',false);assert.throws(()=>prepare(root),/재검토/);const output=path.join(root,'old');fs.mkdirSync(output);fs.writeFileSync(path.join(output,'sentinel'),'keep');assert.equal(fs.readFileSync(path.join(output,'sentinel'),'utf8'),'keep')})
test('private links and unapproved links block export',t=>{for(const link of ['[private](../00_Drafts/x.md)','[[secret]]']){const {root,write}=fixture(t);write('10_Published/index.md','---\ntitle: Home\ndate: 2026-09-12\ntags: []\ndraft: false\n---\n'+link);assert.throws(()=>prepare(root),/링크|비공개 경로/)}})
test('only approved referenced assets are exported',t=>{const {root,write}=fixture(t);write('assets/public/a.png',Buffer.from('image'));write('assets/public/unused.png',Buffer.from('unused'));write('10_Published/index.md','---\ntitle: Home\ndate: 2026-09-12\ntags: []\ndraft: false\n---\n![a](../assets/public/a.png)');const out=prepare(root);assert.equal(out.size,2);assert.ok(out.has('assets/a.png'));assert.match(out.get('index.md'),/\(assets\/a.png\)/)})
test('symlinks cannot import private content',t=>{const {root}=fixture(t);fs.renameSync(path.join(root,'10_Published/index.md'),path.join(root,'secret.md'));fs.symlinkSync('../secret.md',path.join(root,'10_Published/index.md'));assert.throws(()=>prepare(root),/심볼릭/)} )
test('dry run preserves files and normal sync removes stale exports',t=>{const {root}=fixture(t);const output=path.join(root,'content');fs.mkdirSync(output);fs.writeFileSync(path.join(output,'stale.md'),'old');synchronize(output,prepare(root),true);assert.ok(fs.existsSync(path.join(output,'stale.md')));synchronize(output,prepare(root));assert.ok(!fs.existsSync(path.join(output,'stale.md')));assert.ok(fs.existsSync(path.join(output,'index.md')))})
